env.sast_git_url="https://github.com/harishpallapu/SourceCode_SAST.git"
env.build_git_url="https://github.com/harishpallapu/SourceCode_SAST.git"
env.tomcat_ip="http://mypublicip:8084"
env.functional_web_git_url="https://github.com/harishpallapu/webtest.git"
env.functional_mobile_git_url="https://github.com/harishpallapu/mobiletest.git"
env.jmeter_git_url="https://github.com/harishpallapu/folder.git"
env.nexus_ip="http://localhost:8081"
env.mail_to="nihas0505@gmail.com"
