env.SAST_GIT_URL="https://github.com/harishpallapu/SourceCode_SAST.git"
env.BUILD_GIT_URL="https://github.com/harishpallapu/SourceCode_SAST.git"
env.TOMCAT_IP="http://mypublicip:8084"
env.FUNCTIONAL_WEB_GIT_URL="https://github.com/harishpallapu/webtest.git"
env.FUNCTIONAL_MOBILE_GIT_URL="https://github.com/harishpallapu/mobiletest.git"
