env.SAST_GIT_URL="https://github.com/harishpallapu/SourceCode_SAST.git"
env.FUNCTIONAL_WEB_GIT_URL="https://github.com/harishpallapu/webtest.git"
env.FUNCTIONAL_MOBILE_GIT_URL="https://github.com/harishpallapu/mobiletest.git"
env.JMETER_GIT_URL="https://github.com/harishpallapu/folder.git"
env.TOMCAT_IP="65.0.18.96"
env.NEXUS_IP="13.232.201.239"
env.BUILD_GIT_URL="https://github.com/harishpallapu/SourceCode_SAST.git"
